### ISSUE TITLE
Error in SWAP. BigNumber Error in Metamask

### ISSUE THREAD

**Issue by W1SE95** [xdefilab/xdefi-base#38]
Hello.

I got a metamask error during the next swap in the network test. Do you need such information or is it a metamask problem? (I made screenshots and wrote down the error codes)

`Детали ошибки
Сообщение: new BigNumber() not a base 16 number: undefined

Код: BigNumber Error

Стек:
BigNumber Error: new BigNumber() not a base 16 number: undefined
  at $ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:43:44267)
  at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:43:49784)
  at new H (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:43:41731)
  at E (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:619624)
  at S (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:620308)
  at Function.mapToProps (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:227614)
  at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:93:20755)
  at Function.n.mapToProps (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:93:20891)
  at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:93:20755)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:93:19596
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:93:12990
  at Object.useMemo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:63534)
  at useMemo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:136:5250)
  at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:93:12934)
  at ca (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:59367)
  at Ga (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:67589)
  at Va (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:67408)
  at Ua (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:67127)
  at jl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:107861)
  at bu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:90053)
  at pu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:89978)
  at iu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:87326)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45768
  at r.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:172:3472)
  at Vo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45477)
  at Yo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45713)
  at Ko (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45648)
  at le (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:114525)
  at Er (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:29321)
  at HTMLDocument.c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/initSentry.js:1:10461)`

![1](https://user-images.githubusercontent.com/60783381/110831839-4e4ecf80-82a3-11eb-8244-8c48ea9b246d.jpg)
![2](https://user-images.githubusercontent.com/60783381/110831842-4ee76600-82a3-11eb-92ec-462cc5d8ef9c.jpg)
![3](https://user-images.githubusercontent.com/60783381/110831843-4f7ffc80-82a3-11eb-99aa-ae1449e97d31.jpg)

**Comment by lavender78** [comment]
Hello, this problem is caused by MetaMask's error in generating transaction gas fee. It is suggested to clean up the transaction record of MetaMask's current account. The specific actions are as follows:
1 Click the account icon
![image](https://user-images.githubusercontent.com/66249837/110900013-0a100d80-833d-11eb-84b9-00a9b89c1960.png)

2. Click Settings 
![image](https://user-images.githubusercontent.com/66249837/110900040-198f5680-833d-11eb-9511-1f9a4b3773d0.png)
3 Click Advanced
![image](https://user-images.githubusercontent.com/66249837/110900077-2744dc00-833d-11eb-96f5-5818fa44d060.png)

4 Click Reset Account
![image](https://user-images.githubusercontent.com/66249837/110900117-33309e00-833d-11eb-8d00-ce8cb395869b.png)
